apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-bucket
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-bucket-server.default.svc.cluster.local
    path: "/"
